# Generated by Django 4.2.6 on 2023-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothShop', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Обрабатывается'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('returned', 'Возвращен'), ('return_request', 'Запрос на возврат')], default='processing', max_length=20),
        ),
    ]
