# Generated by Django 4.2.6 on 2023-12-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothShop', '0009_remove_order_address_remove_order_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('adidas', 'Адидас'), ('Nike', 'Найк')], default='Adidas', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Blue', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', '42'), ('M', '44'), ('L', '46'), ('XL', '48'), ('XXL', '50'), ('XXXL', '52')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
