# Generated by Django 4.2.6 on 2023-12-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothShop', '0012_alter_product_brand_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('', ''), ('adidas', 'Адидас'), ('Nike', 'Найк')], default='', max_length=100),
        ),
    ]
